language: go
sudo: required

go:
  - 1.4
  - 1.5
  - 1.6

env:
  - DOCKER_HOST=unix:///var/run/docker.sock

services:
  - docker

before_install:
  - docker pull microscaling/priority-1:latest

install: make get-deps
